name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          format: gcc
          severity: warning

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test action (dry run)
        uses: ./
        with:
          kas_file: test/kas/minimal.yml
          kas_cmd: dump
        continue-on-error: true

  # TODO: Add integration tests with actual kas builds
  # This requires creating test kas files and potentially
  # using self-hosted runners for resource-intensive builds
