name: Test Action

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]

jobs:
  test-dump:
    name: Test kas dump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test action (dump config only)
        uses: ./  # Uses our local action
        with:
          kas_file: test/kas/minimal.yml
          kas_cmd: dump

  test-checkout:
    name: Test kas checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test action (checkout repos only)
        uses: ./
        with:
          kas_file: test/kas/minimal.yml
          kas_cmd: checkout
          
      - name: Verify checkout worked
        run: |
          ls -la
          # Should see poky directory
          test -d poky && echo "✅ Poky checked out" || echo "❌ Poky missing"
